version: '3.9'

services:
  jupyter:
    build: .
    image: antonioanerao/jupyter-stable-diffusion:latest
    ports:
      - ${JupyterPort}:${JupyterPort}
    volumes:
      - ./project:/project
    command: jupyter lab --ip=0.0.0.0 --port=${JupyterPort} --allow-root --NotebookApp.token='${JupyterAppToken}'
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
